### PR TITLE
Switch wifi services to be protobuf based

### PR DESCRIPTION
**Pull request by madninja**
This switches the wifi ervices characteristic from json to protobuf.

### CODE REVIEW

**Comment by Vagabond** [comment]
Why is this being done?

**Comment by madninja** [comment]
@Vagabond we use protobuf in most newer characteristics.. This makes it more consistent and packs in more wifi ssids at the same time.

**Comment by madninja** [comment]
And since I'd already broken the characteristic by inadvertently removing `jsx` it seemed like an opportune time

**Comment by Vagabond** [comment]
I guess this looks ok?

**Pull request merged**
